### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by 1257331501** [hACKbUSTER/UberGuide-iOS#1]
<AVOSCloud/AVOSCloud.h> file not found  "UBERGuide-Swift.h" file not found. xcode7.2 模拟器6sp 9.2

**Comment by SergioChan** [comment]
你把Realm和AVOS的静态库手动添加进项目根目录一下。。因为文件太大了所以我们加进了gitignore，需要引入这两个框架，虽然暂时没用到Realm只用到了Leancloud的客户端sdk
