### ISSUE TITLE
Retina imagify your readme.me 

### ISSUE THREAD

**Issue by eonist** [hACKbUSTER/UberGuide-iOS#3]
I.e:

```


<img width="410" alt="img" src="https://dl.dropboxusercontent.com/u/2559476/colorpanel_el_cap.mov.gif">
```

This img is originally 820 so of you set it to 410...then it looks perfect on retina screens.

**Comment by JustinFincher** [comment]
Hi, screenshots are now set to 621px width, thank you. :-)
hACKbUSTER/UberGuide-iOS@6e9d145f8688498fdd77288dc275f51560d5dc68

**Comment by eonist** [comment]
Np
